[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", default-features = false, features = ["rwh_05", "x11"] }
ash = { version = "0.37", features = ["linked"] }
ash-window = "0.12.0"
raw-window-handle = "0.5.2"
