[package]
name = "rustfun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russh = "0.43.0"
tokio = "1.36.0"
async-trait = "0.1.78"
anyhow = "1.0.81"